# 테스트 및 디버깅을 위한 작은 설정

defaults:
  - config

# 더 작은 데이터셋/더 빠른 학습을 위한 재정의
data:
  batch_size: 128

model:
  embed_dim: 32
  layer_dims: [16, 8]

training:
  max_epochs: 50
  check_val_every_n_epoch: 2
  log_every_n_steps: 20